# Generated by Django 5.1.2 on 2024-11-05 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camapnhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personagem', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('aparencia', models.TextField(blank=True, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_de_pontos', models.IntegerField(default=0)),
                ('pontos_de_experiencia_guardados', models.IntegerField(default=0)),
                ('pontos_de_vantagens', models.IntegerField(default=0)),
                ('pontos_de_desvantagens', models.IntegerField(default=0)),
                ('pontos_de_pericias', models.IntegerField(default=0)),
                ('pontos_de_atributos', models.IntegerField(default=0)),
                ('st', models.IntegerField(default=10)),
                ('xpst', models.IntegerField(default=0)),
                ('dx', models.IntegerField(default=10)),
                ('xpdx', models.IntegerField(default=0)),
                ('iq', models.IntegerField(default=10)),
                ('xpiq', models.IntegerField(default=0)),
                ('ht', models.IntegerField(default=10)),
                ('xpht', models.IntegerField(default=0)),
                ('damage', models.CharField(blank=True, max_length=50, null=True)),
                ('basic_lift_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hp', models.IntegerField(default=10)),
                ('will', models.IntegerField(default=10)),
                ('perception', models.IntegerField(default=10)),
                ('fp', models.IntegerField(default=10)),
                ('basic_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('basic_move', models.IntegerField(default=5)),
                ('advantages', models.TextField(blank=True, null=True)),
                ('disadvantages', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('equipments', models.TextField(blank=True, null=True)),
                ('campanha', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='gurps.campanha')),
                ('nome_jogador', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha do Personagem',
                'verbose_name_plural': 'Fichas dos Personagens',
            },
        ),
    ]
