# Generated by Django 5.1.2 on 2024-11-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0002_camapnhas_campanha_fichapersonagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camapnhas',
        ),
    ]
