# Generated by Django 5.1.2 on 2024-11-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0004_fichapersonagem_tl'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='regras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campanha',
            name='tl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campanha',
            name='xp_acumulado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campanha',
            name='xp_inicial',
            field=models.IntegerField(default=0),
        ),
    ]
