# Generated by Django 5.1.2 on 2024-11-11 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0007_alter_fichapersonagem_campanha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichapersonagem',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gurps.campanha'),
        ),
        migrations.AlterField(
            model_name='fichapersonagem',
            name='nome_jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
