# Generated by Django 5.1.2 on 2024-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0010_alter_fichapersonagem_campanha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
