# Generated by Django 5.1.2 on 2024-11-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0013_alter_campanha_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='campanhas/'),
        ),
    ]
