# Generated by Django 5.1.2 on 2024-11-13 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0014_alter_campanha_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to=settings.AUTH_USER_MODEL),
        ),
    ]
