# Generated by Django 5.1.2 on 2024-11-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0015_campanha_dono'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('appearance_age', models.JSONField()),
                ('points_summary', models.JSONField()),
                ('attributes', models.JSONField()),
                ('sub_attributes', models.JSONField()),
                ('advantages', models.JSONField()),
                ('disadvantages', models.JSONField()),
                ('skills', models.JSONField()),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('background', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='character_photos/')),
                ('equipment_melee', models.JSONField()),
                ('equipment_ranged', models.JSONField()),
                ('equipment_armor', models.JSONField()),
                ('maneuvers_melee', models.JSONField()),
                ('maneuvers_ranged', models.JSONField()),
                ('maneuvers_defense', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='FichaPersonagem',
        ),
    ]
