# Generated by Django 5.1.2 on 2024-11-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0016_charactersheet_delete_fichapersonagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='advantages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='appearance_age',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='disadvantages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='equipment_armor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='equipment_melee',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='equipment_ranged',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='maneuvers_defense',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='maneuvers_melee',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='maneuvers_ranged',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='points_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='sub_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
