# Generated by Django 5.1.2 on 2024-11-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0017_alter_charactersheet_advantages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactersheet',
            old_name='name',
            new_name='nome_personagem',
        ),
    ]
