# Generated by Django 5.1.2 on 2024-11-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0019_rename_nome_personagem_charactersheet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactersheet',
            old_name='name',
            new_name='nome_personagem',
        ),
    ]
