# Generated by Django 5.1.2 on 2024-11-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0022_rename_points_summary_charactersheet_pontos_soma'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='info_campanha',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
