# Generated by Django 5.1.2 on 2024-11-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0023_charactersheet_info_campanha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactersheet',
            old_name='attributes',
            new_name='atributos',
        ),
    ]
