# Generated by Django 5.1.2 on 2025-01-23 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0025_grupo_chat_mensagens_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagens_grupo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='mensagens_grupo',
            name='autor',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Grupo_Chat',
        ),
        migrations.DeleteModel(
            name='Mensagens_Grupo',
        ),
    ]
