# Generated by Django 5.1.2 on 2025-01-23 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0026_remove_mensagens_grupo_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='gurps.campanha'),
        ),
    ]
