# Generated by Django 5.1.2 on 2025-02-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0028_camapanhaassets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CamapanhaAssets',
            new_name='CampanhaAssets',
        ),
    ]
