# Generated by Django 5.1.2 on 2025-02-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0029_rename_camapanhaassets_campanhaassets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhaassets',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
