# Generated by Django 5.1.2 on 2025-02-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0030_alter_campanhaassets_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhaassets',
            name='slot',
            field=models.IntegerField(default=1),
        ),
    ]
