# Generated by Django 5.1.2 on 2025-02-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0031_campanhaassets_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='imagem',
            field=models.ImageField(default='campanhas/default.jpg', upload_to='campanhas/'),
        ),
    ]
