# Generated by Django 5.1.2 on 2025-02-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0032_alter_campanha_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='imagem',
            field=models.ImageField(upload_to='campanhas/'),
        ),
    ]
