# Generated by Django 5.1.2 on 2025-02-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0035_alter_campanha_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='nome_personagem',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
