# Generated by Django 5.1.2 on 2025-02-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0036_alter_campanha_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhaassets',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='gurps.campanha', unique=True),
        ),
    ]
