# Generated by Django 5.1.2 on 2025-02-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0039_alter_charactersheet_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campanha',
            old_name='xp_inicial',
            new_name='xp_da_campanha',
        ),
    ]
