# Generated by Django 5.1.2 on 2025-03-04 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0041_rename_xp_da_campanha_campanha_pontos_de_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='campanhaassets',
            name='campanha',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='gurps.campanha'),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='nome_personagem',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='username',
            field=models.CharField(help_text='Digite um nome de usuário único para login com no máximo 10 caracteres.', max_length=10, unique=True, verbose_name='Nome de usuário'),
        ),
    ]
