# Generated by Django 5.1.2 on 2025-03-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0042_alter_campanha_nome_alter_campanhaassets_campanha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='username',
            field=models.CharField(help_text='Digite um nome de usuário único para login com no máximo 10 caracteres.', max_length=20, unique=True, verbose_name='Nome de usuário'),
        ),
    ]
