# Generated by Django 5.1.2 on 2025-03-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0043_alter_registeruser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='username',
            field=models.CharField(help_text='Digite um nome de usuário único para login com no máximo 20 caracteres.', max_length=20, unique=True, verbose_name='Nome de usuário'),
        ),
    ]
