# Generated by Django 5.1.2 on 2025-03-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0044_alter_registeruser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhaassets',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
