# Generated by Django 5.1.2 on 2025-03-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0049_alter_campanhaassets_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='regras',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='campanhaassets',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
