# Generated by Django 5.1.2 on 2025-04-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0050_alter_campanha_descricao_alter_campanha_regras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='descricao',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='regras',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
