# Generated by Django 5.1.2 on 2025-04-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurps', '0052_alter_campanhaassets_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhaassets',
            name='description',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
