# Generated by Django 5.1.2 on 2026-04-21 18:20

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gurps', '0054_savestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=200)),
                ('chapter', models.CharField(blank=True, max_length=200)),
                ('section', models.CharField(blank=True, max_length=500)),
                ('page_start', models.PositiveIntegerField()),
                ('page_end', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('tokens', models.PositiveIntegerField()),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='rule_chunk_emb_hnsw', opclasses=['vector_cosine_ops']), models.Index(fields=['book', 'page_start'], name='rag_rulechu_book_c34d48_idx')],
                'constraints': [models.UniqueConstraint(fields=('book', 'text_hash'), name='unique_chunk_per_book')],
            },
        ),
        migrations.CreateModel(
            name='EntityEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('scope', models.CharField(choices=[('public', 'Público'), ('campanha', 'Campanha'), ('gm_only', 'Apenas GM')], default='campanha', max_length=20)),
                ('text', models.TextField()),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('embedding_model', models.CharField(default='paraphrase-multilingual-MiniLM-L12-v2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_embeddings', to='gurps.campanha')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='entity_emb_hnsw', opclasses=['vector_cosine_ops']), models.Index(fields=['content_type', 'object_id'], name='rag_entitye_content_e15f76_idx'), models.Index(fields=['campanha', 'scope'], name='rag_entitye_campanh_a42872_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_embedding_per_entity')],
            },
        ),
    ]
